### ISSUE TITLE
Trouble in installing psychopy

### ISSUE THREAD

**Issue by ngctnnnn** [waltervanheuven/psychopy-on-M1#1]
Thanks for making this tutorial, however I still receive errors install these packages: pocketsphinx, psychtoolbox, pyo, grpcio

**Comment by waltervanheuven** [comment]
I've updated the instructions and added also instructions for PsychoPy version 2022.1.1.

**Comment by ngctnnnn** [comment]
I did follow to the instructions. On installing pyo from source, I have received errors:

`In file included from src/engine/ad_coreaudio.c:21:      
In file included from include/ad_coreaudio.h:25:     
include/servermodule.h:31:10: fatal error: 'sndfile.h' file not found       
#include "sndfile.h"       
         ^~~~~~~~~~~       
1 error generated.        
error: command '/usr/bin/clang' failed with exit code 1`

**Comment by ngctnnnn** [comment]
Oh I have succeeded in installing Psychopy. Thanks a lot for making this repo. I will close this issue here.
