### ISSUE TITLE
unable to install pyo

### ISSUE THREAD

**Issue by naiqixiao** [waltervanheuven/psychopy-on-M1#2]
Hi there,

Thanks so much for showing how to install native PsychoPy on M1 Macs. I followed the instruction but had an error when I tried to install pyo with pip.

The error message showed `include/servermodule.h:31:10: fatal error: 'sndfile.h' file not found`

Could you look into this issue and let me know how to address it?

Thanks,
Gabriel

**Comment by waltervanheuven** [comment]
Building `pyo` from source should fix this issue.

### Install `pyo` library from source

```sh
brew install liblo libsndfile portaudio portmidi fftw
git clone https://github.com/belangeo/pyo.git
cd pyo
```

Add the following line to the file `include/ad_coreaudio.h` after line 24:

```txt
#include <CoreAudio/HostTime.h>
```

Next, install pyo from source.

```sh
export LDFLAGS=-L"$(brew --prefix)/lib"
export CFLAGS="-I/$(brew --prefix)/include"
export CXXFLAGS="-I/$(brew --prefix)/include"
python setup.py install --use-coreaudio --use-double
```

**Comment by naiqixiao** [comment]
Thanks!

I also found this is the key to solve the issue: 
`brew install libsndfile`
