### ISSUE TITLE
clang error: no such file or directory: 'PsychSourceGL/Cohorts/PortAudio/libportaudio_osx_64.a'

### ISSUE THREAD

**Issue by awellis** [waltervanheuven/psychopy-on-M1#3]
Hi, I tried to follow your instructions, but I got this:
```
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                     ^
2 warnings generated.
clang: error: no such file or directory: 'PsychSourceGL/Cohorts/PortAudio/libportaudio_osx_64.a'
error: Setup script exited with error: command '/usr/bin/clang' failed with exit code 1
```

I didn't completely follow your instructions, thought. I'm using Python 3.9 installed with Mamba. Would you expect that that has something to do with it?

**Comment by bwchen05** [comment]
Same issue. Have you solved this problem?

**Comment by awellis** [comment]
Not yet. I ended up just using the standalone version for now.

**Comment by waltervanheuven** [comment]
When did this error occur? Did you install the latest version of PsychTooBox from source in step 9?
