### ISSUE TITLE
Failed to import psychToolbox

### ISSUE THREAD

**Issue by Tongzhao9417** [waltervanheuven/psychopy-on-M1#6]
Hey, it's me again :) I have two questions want to ask.

1. How to start Psychopy after exit Psychopy?
I followed your step and run psychopy successfully. But how could start it again? My way is run psychopy in /venv/bin/psychopy, is this correct way?

2. I failed to run any psyexp file. The error info is 
```
1.0450     WARNING     The 'psychtoolbox' library cannot be loaded but is required for audio capture (use `pip install psychtoolbox` to get it). Microphone recording will be unavailable this session. Note that opening a microphone stream will raise an error.
Traceback (most recent call last):
1.0472     ERROR     Failed to load any of the audioLibs: ['ptb']. Falling back to PsychToolbox ('ptb') backend for sound. Be sure to add 'ptb' to preferences to avoid seeing this message again.
1.0493     ERROR     No audioLib could be loaded. Tried: ['ptb']
 Check whether the necessary audioLibs are installed
  File "/Users/tongzhao/Documents/untitled_lastrun.py", line 21, in <module>
    from psychopy import sound, gui, visual, core, data, event, logging, clock, colors, layout
  File "/Users/tongzhao/Documents/Psychopy/psychopy-on-M1/venv/lib/python3.10/site-packages/psychopy/sound/__init__.py", line 214, in <module>
    if audioLib.lower() != 'ptb':
AttributeError: 'NoneType' object has no attribute 'lower'
################ Experiment ended with exit code 1 [pid:97485] #################
73.9589     INFO     Loaded monitor calibration from ['2023_07_25 11:09']
```
The trial doesn't include any audio stimulation.

**Comment by waltervanheuven** [comment]
To start PsychoPy again, activate the venv with `source venv/bin/activate` and then enter `psychopy`.

Please note that there are issues with ptb and vsync. The Apple silicon build of PsychoPy is unable to detect vsync and timing is likely not reliable. Furthermore, PsychoPy v2023.2.0 does not seem to detect `pyo` as an option for audio devices. Audio seems to fall back to ptb and ptb does not support Apple silicon. Audio was working with previous version of PsychoPy. The Apple silicon build of PsychoPy has lots of issues at the moment.

Use the Rosetta version of PsychoPy until the issues have been resolved.

**Comment by Tongzhao9417** [comment]
Thanks a lot!
I closed this issue
